sudo: false

env:
  - CXX=g++-4.9
  - CXX=clang++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

language: node_js

os:
  - linux
  - osx

osx_image: xcode10

node_js:
  - "8"
  - "9"
  - "10"
  - "12"

jobs:
  exclude:
      - os: osx
        env: CXX=g++-4.9
      - os: linux
        env: CXX=clang++

install:
  - npm install --build-from-source

after_success:
  - npm install coveralls
  - nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls

deploy:
  provider: script
  script:
    - npm run upload-posix
  skip_cleanup: true
  on:
    tags: true
    repo: node-ffi-napi/node-ffi-napi
